export const LOGIN = 'APP:LOGIN'
export const LOGOUT = 'APP:LOGOUT'

export const SET_CAT = 'APP:STATIC:CAT:SET'

export const SET_USER = 'USER:SET'
export const REMOVE_USER = 'USER:REMOVE'

export const SET_MESS = 'ALERT:MESS:SET'
export const SET_ERROR = 'ALERT:ERROR:SET'
export const CLEAR_MESS = 'ALERT:MESS:CLEAR'
export const CLEAR_ERROR = 'ALERT:ERROR:CLEAR'


export const SET_DEVICES = 'DEVICES:SET'
export const SET_CONTRACT = 'CONTRACT:SET'


export const PUSH_DEVICE = 'DEVICES:PUSH'
export const REMOVE_DEVICES = 'DEVICES:REMOVE'

export const SET_CURRENT_DEVICE = 'DEVICES:CURRENT'

export const SET_AUCTION_FILTER_CASES = 'FILTER:AUCTION:CASES:SET'
export const SET_AUCTION_FILTER_DATE = 'FILTER:AUCTION:DATE:SET'
export const SET_AUCTION_FILTER_BETS = 'FILTER:AUCTION:BETS:SET'

export const SET_ORDER_FILTER_STATUS = 'FILTER:ORDER:STATUS:SET'
export const SET_ORDER_FILTER_CASES = 'FILTER:ORDER:CASES:SET'
export const SET_ORDER_FILTER_DATE = 'FILTER:ORDER:DATE:SET'
